from langchain_core.messages import HumanMessage, AIMessage, ToolMessage, AnyMessage, BaseMessage, SystemMessage
from langgraph.types import Command, Send
from typing import Literal
from data_models import State
from prompts import CIA_PROMPT
from llm_models import cia_model
from IPython.display import display, Markdown
def orchestrator_node(state: State) -> Command[Literal["worker"]]:
    """
    Orchestrator decomposes the problem defined by the specialized agent.
    """
    print(f"🧠 Orchestrator invoked by {state.current_requesting_agent}")

    if not state.orchestrator_orders:
        print("⚠️ No orchestrator orders provided. Returning to specialized agent.")
        return Command(
            update={"messages": ["⚠️ No orders provided to the orchestrator."]},
            goto=state.current_requesting_agent
        )

    messages = [
        SystemMessage(CIA_PROMPT),
        HumanMessage(state.orchestrator_orders[-1]), #TODO: check it does not bug with removal of [] in generation agent
        HumanMessage(
            "Based on these orders, decompose the problem into engineering tasks. "
            "Return the tasks in JSON format using the OrchestratorDecision schema."
        )
    ]

    print("🟢 Invoking CIA model to generate tasks...")
    cia_output = cia_model.invoke(messages)

    display(Markdown(f"**CIA Response:** {cia_output.response}"))

    if not cia_output.research_tasks:
        print("⚠️ No tasks generated. Returning to specialized agent.")
        return Command(
            update={
                "messages": [cia_output.response, "⚠️ No tasks were generated by the orchestrator."],
            },
            goto=state.current_requesting_agent
        )

    # Inject return_to_agent into all tasks
    # We are sure that agent name is correct
    for task in cia_output.research_tasks:
        task.return_to_agent = state.current_requesting_agent

    task_count = len(cia_output.research_tasks)
    print(f"🟢 Dispatching {task_count} tasks to Worker Agents.")

    return Command(
        update={
            "messages": [cia_output.response],
            "current_tasks_count": task_count
        },
        goto=[Send("worker", task) for task in cia_output.research_tasks]
    )